/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: 51f2a0a67469d60b1ad0726fd4f077ad)
interface __BaseEnv_CloudflareBindings {
	IMAGES: KVNamespace;
	DB: D1Database;
	ROOM_CREATE_RATE_LIMITER: RateLimit;
	API_RATE_LIMITER: RateLimit;
	ROOM_IMAGE_RATE_LIMITER: RateLimit;
	SOCKET_RATE_LIMITER: RateLimit;
	CHAT_ROOMS: DurableObjectNamespace<import("./src/index").ChatRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ChatRoom";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
