/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: db7f73b225d828c1556db3ed1b67e97d)
interface __BaseEnv_CloudflareBindings {
	IMAGES: KVNamespace;
	DB: D1Database;
	ROOM_CREATE_RATE_LIMITER: RateLimit;
	BETTER_AUTH_URL: "";
	BETTER_AUTH_SECRET: "";
	CHAT_ROOMS: DurableObjectNamespace<import("./src/index").ChatRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ChatRoom";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET">> {}
}
