/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: e888653cc0b195f0b21d9e4546cbadf7)
interface __BaseEnv_CloudflareBindings {
	IMAGES: R2Bucket;
	DB: D1Database;
	BETTER_AUTH_URL: "";
	BETTER_AUTH_SECRET: "";
	CHAT_ROOMS: DurableObjectNamespace /* ChatRoom */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET">> {}
}
